#!/usr/bin/env python3
"""Scan files for public-release blockers before they leave a private workspace."""

from __future__ import annotations

import argparse
import datetime as dt
import html
import json
import os
import re
import sys
import traceback
import zipfile
from dataclasses import asdict, dataclass
from pathlib import Path
from xml.etree import ElementTree


TEXT_EXTENSIONS = {
    ".bash",
    ".bat",
    ".c",
    ".cc",
    ".cfg",
    ".cmd",
    ".conf",
    ".cpp",
    ".cs",
    ".css",
    ".env",
    ".go",
    ".h",
    ".hpp",
    ".ini",
    ".java",
    ".js",
    ".jsx",
    ".kt",
    ".lock",
    ".md",
    ".mjs",
    ".php",
    ".ps1",
    ".txt",
    ".csv",
    ".tsv",
    ".json",
    ".yaml",
    ".yml",
    ".html",
    ".htm",
    ".py",
    ".r",
    ".rs",
    ".scss",
    ".sh",
    ".sql",
    ".toml",
    ".ts",
    ".tsx",
    ".qmd",
    ".tex",
    ".xml",
}
TEXT_FILENAMES = {
    ".env",
    ".env.local",
    ".env.production",
    ".env.staging",
    ".gitignore",
    ".npmrc",
    ".pypirc",
    "Cargo.lock",
    "Cargo.toml",
    "Dockerfile",
    "Gemfile",
    "Makefile",
    "Pipfile",
    "go.mod",
    "go.sum",
    "package-lock.json",
    "package.json",
    "pnpm-lock.yaml",
    "pyproject.toml",
    "requirements.txt",
    "tsconfig.json",
    "yarn.lock",
}
TEXT_FILENAMES_LOWER = {name.lower() for name in TEXT_FILENAMES}
OFFICE_EXTENSIONS = {".docx", ".xlsx", ".pptx"}
PDF_EXTENSIONS = {".pdf"}
SUPPORTED_EXTENSIONS = TEXT_EXTENSIONS | OFFICE_EXTENSIONS | PDF_EXTENSIONS
BLOCKING_SEVERITIES = {"high", "medium"}
SKIP_DIR_NAMES = {
    ".git",
    ".hg",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "node_modules",
    "venv",
}


@dataclass
class Finding:
    file: str
    location: str
    severity: str
    rule: str
    snippet: str
    suggestion: str
    allowed: bool = False
    reason: str = ""


@dataclass
class ExtractionIssue:
    file: str
    issue: str
    detail: str


@dataclass(frozen=True)
class Rule:
    rule: str
    severity: str
    pattern: re.Pattern[str]
    suggestion: str


def compile_rules() -> list[Rule]:
    flags = re.IGNORECASE | re.MULTILINE
    raw_rules = [
        (
            "SECRET_OR_CREDENTIAL",
            "high",
            r"\b(api[_-]?key|secret[_-]?key|access[_-]?token|refresh[_-]?token|private[_-]?key|client[_-]?secret|password|passwd|credential|database_url|db_password|jwt_secret|session_secret|cookie|set-cookie|npm_token|pypi_token|aws_access_key_id|aws_secret_access_key|openai_api_key|anthropic_api_key|github_token|hf_token)\b|Authorization:\s*Bearer|-----BEGIN (?:RSA |OPENSSH |EC |DSA )?PRIVATE KEY-----|sk-[A-Za-z0-9_-]{16,}|sk-ant-[A-Za-z0-9_-]{16,}|AKIA[0-9A-Z]{16}|ASIA[0-9A-Z]{16}|gh[pousr]_[A-Za-z0-9_]{20,}|github_pat_[A-Za-z0-9_]{30,}|xox[baprs]-[A-Za-z0-9-]{20,}|hf_[A-Za-z0-9]{20,}|AIza[0-9A-Za-z_-]{20,}|eyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{10,}",
            "Remove credentials or secret-like material; rotate if a real secret was exposed.",
        ),
        (
            "LOCAL_PATH_OR_PRIVATE_LOCATION",
            "high",
            r"(?<![A-Za-z0-9])(?:[A-Z]:[\\/]|\\\\[A-Za-z0-9._-]+[\\/])|C:[\\/]Users[\\/]|/Users/[^ \t\r\n]+|/home/[^ \t\r\n]+|AppData[\\/]|\.codex[\\/]|\.cowork_chat|codex-clipboard|Temp[\\/]|OneDrive[\\/].*Desktop",
            "Remove local machine paths and private workspace locations.",
        ),
        (
            "PRIVATE_URL_OR_HOST",
            "medium",
            r"\b(?:https?://)?(?:localhost|127\.0\.0\.1|0\.0\.0\.0|10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|172\.(?:1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3})(?::\d+)?\b|\b(?:dev|staging|internal|intranet|corp|vpn)[.-][A-Za-z0-9.-]+\b",
            "Remove private hosts, local URLs, and environment-specific endpoints unless they are intentional public examples.",
        ),
        (
            "INTERNAL_PROCESS_OR_CHAT_TRACE",
            "high",
            r"\b(send|sent|handoff|waiting|route|ask|tell)\s+(the\s+)?(user|owner|reviewer|assistant|agent)\b|chat\s*(log|transcript|notes)|internal\s+(review|routing|decision|discussion)|who\s+decided|用户拍板|交给用户|发给|待.*审|回复|内部讨论|内部流程|聊天记录|同步进度|你先|你可以|请你|我会|我已经|咱们",
            "Rewrite from a public-reader perspective; remove internal routing, chat, and decision-process language.",
        ),
        (
            "AI_OR_AGENT_TRACE",
            "medium",
            r"\b(Codex|Claude|DeepSeek|ChatGPT|GPT-?[0-9A-Za-z.]*|Gemini|Copilot|LLM|AI assistant|AI-generated|generated by AI|agent run|cowork|system prompt|prompt used|model response|as an AI)\b|AI\s*协作|AI\s*痕迹|AI生成|大模型协作|提示词|系统提示词|模型回复|智能体",
            "Remove internal AI/collaboration traces or move required disclosure into a deliberate public statement.",
        ),
        (
            "TOOL_OR_RUNTIME_TRACE",
            "medium",
            r"\b(Thinking|Tool actions?|Browser Console|Captured page snapshot|API call failed after \d+ retries|Ran\s*[·:])\b|browser_snapshot|browser_vision|terminal-agent|agent-browser|思考中|工具调用|正在重新连接",
            "Remove agent/tool execution traces, logs, and UI status text from public artifacts.",
        ),
        (
            "NON_PUBLIC_TONE_OR_DIRECTIVE",
            "medium",
            r"\b(as requested|per your request|you asked|the user (?:asked|said|requested|approved)|let me|i(?:'ll|'ve| am| can| will| would| have| already)\b|here(?:'s| is) (?:the|a) (?:fixed|updated|requested))\b|按你(?:的)?要求|如你所说|你让我|你问|帮我|请你|我(?:来|会|已经|帮你|给你|建议)|已为你|下面是",
            "Rewrite assistant-facing or chat-facing wording into neutral public prose.",
        ),
        (
            "DRAFT_OR_REVIEW_NOTE",
            "high",
            r"(?<![A-Za-z0-9])(?:DRAFT[_ -]?INTERNAL|FINAL[_ -]?REVIEW|review[_ -]?only|internal[_ -]?only|do[_ -]?not[_ -]?(?:publish|release)|confidential[_ -]?draft|draft[_ -]?only|not[_ -]?for[_ -]?publication)(?![A-Za-z0-9])|审核备注|审查意见|仅供内部|内部版本|草稿勿传|勿公开|勿传|待审",
            "Remove review-only or draft-only notes before release.",
        ),
        (
            "PLACEHOLDER",
            "high",
            r"\b(TODO|TBD|FIXME|XXX|PLACEHOLDER|REPLACE_ME|FILL_ME|lorem ipsum)\b|\[待填写\]|\[待补\]|待补|占位|需补|待定|未定稿",
            "Resolve placeholders before release.",
        ),
        (
            "INTERNAL_FILENAME_OR_LABEL",
            "high",
            r"(?<![A-Za-z0-9])(?:decision[_ -]?packet|task[_ -]?packet|internal[_ -]?package|co-?author[_ -]?decision|review[_ -]?copy|working[_ -]?copy|supplement-?extraction[_ -]?records|stage[0-9]+_(?:live|preflight|round[0-9]+)|round\s*[0-9]+|DRAFT[_ -]?INTERNAL|FINAL[_ -]?REVIEW)(?![A-Za-z0-9])|中文审核版|任务单|决策包|内部包|审核版",
            "Remove internal filenames, package labels, and workflow labels; use neutral public artifact names.",
        ),
        (
            "PRIVATE_ID_OR_ROW_REFERENCE",
            "medium",
            r"\b(pid|paper_id|row_id|internal_id|target_id|screening_id|record_id|local_id|ticket_id)\b|target\s*[\(\[]\s*\d{3,}\s*[\)\]]|内部编号|私有编号|行号",
            "Convert private IDs into documented public identifiers or remove them.",
        ),
        (
            "POSSIBLE_PERSONAL_DATA",
            "low",
            r"\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b|\b(?:\+?\d{1,3}[-. ]?)?(?:\(?\d{2,4}\)?[-. ]?)?\d{3,4}[-. ]\d{4}\b",
            "Review possible personal contact data and remove it unless release is intentional and permitted.",
        ),
    ]
    return [Rule(name, sev, re.compile(pattern, flags), suggestion) for name, sev, pattern, suggestion in raw_rules]


RULES = compile_rules()
VALID_SEVERITIES = {"high", "medium", "low"}


def normalize_path(path: Path) -> str:
    return str(path.resolve())


def is_text_path(path: Path) -> bool:
    return path.suffix.lower() in TEXT_EXTENSIONS or path.name.lower() in TEXT_FILENAMES_LOWER


def is_supported_path(path: Path) -> bool:
    return is_text_path(path) or path.suffix.lower() in OFFICE_EXTENSIONS or path.suffix.lower() in PDF_EXTENSIONS


def has_skipped_parent(path: Path, root: Path) -> bool:
    try:
        parts = path.relative_to(root).parts[:-1]
    except ValueError:
        parts = path.parts[:-1]
    return any(part.lower() in SKIP_DIR_NAMES for part in parts)


def collect_files(inputs: list[str]) -> tuple[list[Path], list[ExtractionIssue]]:
    files: list[Path] = []
    issues: list[ExtractionIssue] = []
    for item in inputs:
        path = Path(item)
        if not path.exists():
            issues.append(ExtractionIssue(item, "MISSING_INPUT", "Input path does not exist."))
            continue
        if path.is_dir():
            for child in path.rglob("*"):
                if has_skipped_parent(child, path):
                    continue
                if child.is_file() and is_supported_path(child):
                    files.append(child)
        elif path.is_file():
            if is_supported_path(path):
                files.append(path)
            else:
                issues.append(
                    ExtractionIssue(
                        normalize_path(path),
                        "UNSUPPORTED_FILE",
                        f"Explicit input has unsupported extension: {path.suffix or '<none>'}.",
                    )
                )
    return sorted(set(files), key=lambda p: str(p).lower()), issues


def read_text_file(path: Path) -> list[tuple[str, str]]:
    data = path.read_bytes()
    for encoding in ("utf-8-sig", "utf-8", "gb18030", "utf-16"):
        try:
            return [(path.name, data.decode(encoding))]
        except UnicodeDecodeError:
            continue
    return [(path.name, data.decode("utf-8", errors="replace"))]


def xml_to_text(raw: bytes) -> str:
    try:
        root = ElementTree.fromstring(raw)
        return " ".join(piece.strip() for piece in root.itertext() if piece and piece.strip())
    except Exception:
        text = raw.decode("utf-8", errors="ignore")
        text = re.sub(r"<[^>]+>", " ", text)
        return html.unescape(re.sub(r"\s+", " ", text))


def office_members(ext: str) -> list[str]:
    if ext == ".docx":
        return ["word/", "docProps/"]
    if ext == ".xlsx":
        return ["xl/", "docProps/"]
    if ext == ".pptx":
        return ["ppt/", "docProps/"]
    return []


def read_office_file(path: Path) -> list[tuple[str, str]]:
    chunks: list[tuple[str, str]] = []
    prefixes = office_members(path.suffix.lower())
    with zipfile.ZipFile(path) as zf:
        for name in sorted(zf.namelist()):
            if not name.endswith(".xml"):
                continue
            if not any(name.startswith(prefix) for prefix in prefixes):
                continue
            text = xml_to_text(zf.read(name))
            if text.strip():
                chunks.append((name, text))
    return chunks


def read_pdf_file(path: Path) -> list[tuple[str, str]]:
    errors: list[str] = []
    try:
        from pypdf import PdfReader  # type: ignore

        reader = PdfReader(str(path))
        chunks = []
        for idx, page in enumerate(reader.pages, start=1):
            chunks.append((f"page {idx}", page.extract_text() or ""))
        if any(text.strip() for _, text in chunks):
            return chunks
        errors.append("pypdf extracted no text")
    except Exception as exc:
        errors.append(f"pypdf unavailable/failed: {exc}")

    try:
        from PyPDF2 import PdfReader  # type: ignore

        reader = PdfReader(str(path))
        chunks = []
        for idx, page in enumerate(reader.pages, start=1):
            chunks.append((f"page {idx}", page.extract_text() or ""))
        if any(text.strip() for _, text in chunks):
            return chunks
        errors.append("PyPDF2 extracted no text")
    except Exception as exc:
        errors.append(f"PyPDF2 unavailable/failed: {exc}")

    try:
        import pdfplumber  # type: ignore

        chunks = []
        with pdfplumber.open(str(path)) as pdf:
            for idx, page in enumerate(pdf.pages, start=1):
                chunks.append((f"page {idx}", page.extract_text() or ""))
        if any(text.strip() for _, text in chunks):
            return chunks
        errors.append("pdfplumber extracted no text")
    except Exception as exc:
        errors.append(f"pdfplumber unavailable/failed: {exc}")

    raise RuntimeError("UNSCANNABLE_PDF: " + " | ".join(errors))


def extract_text(path: Path) -> list[tuple[str, str]]:
    ext = path.suffix.lower()
    if is_text_path(path):
        return read_text_file(path)
    if ext in OFFICE_EXTENSIONS:
        return read_office_file(path)
    if ext in PDF_EXTENSIONS:
        return read_pdf_file(path)
    raise RuntimeError(f"Unsupported file extension: {ext}")


def load_allowlist(path: str | None) -> list[dict[str, str]]:
    if not path:
        return []
    data = json.loads(Path(path).read_text(encoding="utf-8-sig"))
    if not isinstance(data, list):
        raise ValueError("Allowlist must be a JSON list.")
    required = {"rule", "file", "text", "reason"}
    cleaned = []
    for idx, item in enumerate(data, start=1):
        if not isinstance(item, dict) or not required.issubset(item):
            raise ValueError(f"Allowlist entry {idx} must include rule, file, text, and reason.")
        if not str(item["reason"]).strip():
            raise ValueError(f"Allowlist entry {idx} has an empty reason.")
        cleaned.append({key: str(item[key]) for key in required})
    return cleaned


def load_custom_rules(paths: list[str] | None) -> list[Rule]:
    if not paths:
        return []
    flags = re.IGNORECASE | re.MULTILINE
    required = {"rule", "severity", "pattern", "suggestion"}
    custom_rules: list[Rule] = []
    for rule_path in paths:
        data = json.loads(Path(rule_path).read_text(encoding="utf-8-sig"))
        if not isinstance(data, list):
            raise ValueError(f"Rules file must be a JSON list: {rule_path}")
        for idx, item in enumerate(data, start=1):
            if not isinstance(item, dict) or not required.issubset(item):
                raise ValueError(
                    f"Rules entry {idx} in {rule_path} must include rule, severity, pattern, and suggestion."
                )
            name = str(item["rule"]).strip()
            severity = str(item["severity"]).strip().lower()
            pattern = str(item["pattern"])
            suggestion = str(item["suggestion"]).strip()
            if not name:
                raise ValueError(f"Rules entry {idx} in {rule_path} has an empty rule name.")
            if severity not in VALID_SEVERITIES:
                raise ValueError(
                    f"Rules entry {idx} in {rule_path} has invalid severity {severity!r}; use high, medium, or low."
                )
            if not suggestion:
                raise ValueError(f"Rules entry {idx} in {rule_path} has an empty suggestion.")
            try:
                compiled = re.compile(pattern, flags)
            except re.error as exc:
                raise ValueError(
                    f"Rules entry {idx} in {rule_path} has an invalid regex pattern: {exc}"
                ) from exc
            custom_rules.append(Rule(name, severity, compiled, suggestion))
    return custom_rules


def allow_reason(finding: Finding, allowlist: list[dict[str, str]]) -> str:
    normalized = finding.file.replace("\\", "/").lower()
    for entry in allowlist:
        entry_file = entry["file"].replace("\\", "/").lower()
        if entry["rule"] != finding.rule:
            continue
        if entry_file not in normalized:
            continue
        if entry["text"] not in finding.snippet:
            continue
        return entry["reason"]
    return ""


def line_col(text: str, index: int) -> tuple[int, int]:
    line = text.count("\n", 0, index) + 1
    last_newline = text.rfind("\n", 0, index)
    col = index + 1 if last_newline == -1 else index - last_newline
    return line, col


def make_snippet(text: str, start: int, end: int, width: int = 80) -> str:
    lo = max(0, start - width // 2)
    hi = min(len(text), end + width // 2)
    snippet = text[lo:hi].replace("\r", " ").replace("\n", " ")
    snippet = re.sub(r"\s+", " ", snippet).strip()
    return snippet


def scan_text(
    path: Path,
    source: str,
    text: str,
    allowlist: list[dict[str, str]],
    rules: list[Rule],
) -> list[Finding]:
    findings: list[Finding] = []
    for rule in rules:
        for match in rule.pattern.finditer(text):
            line, col = line_col(text, match.start())
            finding = Finding(
                file=normalize_path(path),
                location=f"{source}:line {line}, col {col}",
                severity=rule.severity,
                rule=rule.rule,
                snippet=make_snippet(text, match.start(), match.end()),
                suggestion=rule.suggestion,
            )
            reason = allow_reason(finding, allowlist)
            if reason:
                finding.allowed = True
                finding.reason = reason
            findings.append(finding)
    return findings


def scan_files(
    files: list[Path],
    allowlist: list[dict[str, str]],
    rules: list[Rule],
) -> tuple[list[Finding], list[ExtractionIssue]]:
    findings: list[Finding] = []
    issues: list[ExtractionIssue] = []
    for path in files:
        findings.extend(scan_text(path, "filename", path.name, allowlist, rules))
        try:
            chunks = extract_text(path)
            if not chunks:
                issues.append(ExtractionIssue(normalize_path(path), "NO_EXTRACTED_TEXT", "No text chunks were extracted."))
                continue
            for source, text in chunks:
                findings.extend(scan_text(path, source, text, allowlist, rules))
        except Exception as exc:
            detail = str(exc)
            if path.suffix.lower() == ".pdf" and detail.startswith("UNSCANNABLE_PDF"):
                findings.append(
                    Finding(
                        file=normalize_path(path),
                        location="file",
                        severity="high",
                        rule="UNSCANNABLE_PDF",
                        snippet=detail[:300],
                        suggestion="Export text or install a PDF extraction dependency, then rescan before release.",
                    )
                )
            else:
                issues.append(ExtractionIssue(normalize_path(path), "EXTRACTION_FAILED", detail[:500]))
    return findings, issues


def count_blocking(findings: list[Finding]) -> int:
    return sum(1 for f in findings if not f.allowed and f.severity in BLOCKING_SEVERITIES)


def write_json(path: str | None, payload: dict) -> None:
    if not path:
        return
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def write_markdown_report(
    path: str | None,
    *,
    title: str,
    payload: dict,
    findings: list[Finding],
    issues: list[ExtractionIssue],
    extra_sections: list[str] | None = None,
) -> None:
    if not path:
        return
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# {title}",
        "",
        f"Generated: {payload['generated_at']}",
        f"Scanned files: {payload.get('scanned_file_count', 0)}",
        f"Blocking findings: {payload.get('blocking_findings', 0)}",
        f"Extraction issues: {len(issues)}",
        "",
        "## Findings",
        "",
    ]
    if findings:
        for idx, finding in enumerate(findings, start=1):
            status = "ALLOWLISTED" if finding.allowed else "ACTIVE"
            lines.extend(
                [
                    f"### {idx}. {finding.rule} ({finding.severity}, {status})",
                    "",
                    f"- File: `{finding.file}`",
                    f"- Location: {finding.location}",
                    f"- Snippet: `{finding.snippet}`",
                    f"- Suggestion: {finding.suggestion}",
                ]
            )
            if finding.allowed:
                lines.append(f"- Allowlist reason: {finding.reason}")
            lines.append("")
    else:
        lines.extend(["No rule findings.", ""])

    lines.extend(["## Extraction Issues", ""])
    if issues:
        for issue in issues:
            lines.extend([f"- `{issue.file}`: **{issue.issue}** - {issue.detail}"])
    else:
        lines.append("No extraction issues.")

    lines.extend(
        [
            "",
            "## Manual Public-Release Checklist",
            "",
            "- Confirm this is the intended public artifact, not a renamed internal draft.",
            "- Confirm visible text, filenames, metadata, comments, and hidden notes are public-clean.",
            "- Confirm no secrets, private paths, personal data, placeholders, review notes, or private IDs remain.",
            "- Confirm any AI-use or collaborator disclosure is deliberate and venue-appropriate.",
        ]
    )
    if extra_sections:
        lines.extend([""])
        for section in extra_sections:
            lines.extend([section, ""])
    Path(path).write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def command_scan(args: argparse.Namespace) -> int:
    allowlist = load_allowlist(args.allowlist)
    rules = RULES + load_custom_rules(args.rules)
    files, issues = collect_files(args.inputs)
    findings, extraction_issues = scan_files(files, allowlist, rules)
    issues.extend(extraction_issues)
    blocking = count_blocking(findings)
    payload = {
        "mode": "scan",
        "generated_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "inputs": args.inputs,
        "custom_rules": args.rules or [],
        "scanned_files": [normalize_path(path) for path in files],
        "scanned_file_count": len(files),
        "blocking_findings": blocking,
        "findings": [asdict(finding) for finding in findings],
        "extraction_issues": [asdict(issue) for issue in issues],
    }
    write_json(args.json, payload)
    write_markdown_report(args.report, title="Public Release Scan Report", payload=payload, findings=findings, issues=issues)
    if blocking:
        return 1
    if issues:
        return 2
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Scan files before public release.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    scan = subparsers.add_parser("scan", help="Scan files or directories before public release.")
    scan.add_argument("inputs", nargs="+", help="Files or directories to scan.")
    scan.add_argument("--report", help="Markdown report path.")
    scan.add_argument("--json", help="JSON report path.")
    scan.add_argument("--rules", action="append", help="Optional JSON file with additional rule entries. Repeatable.")
    scan.add_argument("--allowlist", help="Optional JSON allowlist with rule, file, text, reason entries.")
    scan.set_defaults(func=command_scan)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return int(args.func(args))
    except Exception as exc:
        sys.stderr.write(f"ERROR: {exc}\n")
        if os.environ.get("PUBLIC_RELEASE_SANITIZER_DEBUG"):
            traceback.print_exc()
        return 3


if __name__ == "__main__":
    raise SystemExit(main())
